var annotated_dup =
[
    [ "NanoOcp1", "namespaceNanoOcp1.html", [
      [ "Amp5D", "namespaceNanoOcp1_1_1Amp5D.html", [
        [ "dbOcaObjectDef_ChStatus_Gr", "structNanoOcp1_1_1Amp5D_1_1dbOcaObjectDef__ChStatus__Gr.html", "structNanoOcp1_1_1Amp5D_1_1dbOcaObjectDef__ChStatus__Gr" ],
        [ "dbOcaObjectDef_ChStatus_GrHead", "structNanoOcp1_1_1Amp5D_1_1dbOcaObjectDef__ChStatus__GrHead.html", "structNanoOcp1_1_1Amp5D_1_1dbOcaObjectDef__ChStatus__GrHead" ],
        [ "dbOcaObjectDef_ChStatus_Isp", "structNanoOcp1_1_1Amp5D_1_1dbOcaObjectDef__ChStatus__Isp.html", "structNanoOcp1_1_1Amp5D_1_1dbOcaObjectDef__ChStatus__Isp" ],
        [ "dbOcaObjectDef_ChStatus_Ovl", "structNanoOcp1_1_1Amp5D_1_1dbOcaObjectDef__ChStatus__Ovl.html", "structNanoOcp1_1_1Amp5D_1_1dbOcaObjectDef__ChStatus__Ovl" ],
        [ "dbOcaObjectDef_Settings_PwrOn", "structNanoOcp1_1_1Amp5D_1_1dbOcaObjectDef__Settings__PwrOn.html", "structNanoOcp1_1_1Amp5D_1_1dbOcaObjectDef__Settings__PwrOn" ]
      ] ],
      [ "AmpDx", "namespaceNanoOcp1_1_1AmpDx.html", [
        [ "dbOcaObjectDef_ChStatus_GrHead", "structNanoOcp1_1_1AmpDx_1_1dbOcaObjectDef__ChStatus__GrHead.html", "structNanoOcp1_1_1AmpDx_1_1dbOcaObjectDef__ChStatus__GrHead" ]
      ] ],
      [ "AmpDxDy", "namespaceNanoOcp1_1_1AmpDxDy.html", [
        [ "dbOcaObjectDef_ChStatus_Gr", "structNanoOcp1_1_1AmpDxDy_1_1dbOcaObjectDef__ChStatus__Gr.html", "structNanoOcp1_1_1AmpDxDy_1_1dbOcaObjectDef__ChStatus__Gr" ],
        [ "dbOcaObjectDef_ChStatus_Isp", "structNanoOcp1_1_1AmpDxDy_1_1dbOcaObjectDef__ChStatus__Isp.html", "structNanoOcp1_1_1AmpDxDy_1_1dbOcaObjectDef__ChStatus__Isp" ],
        [ "dbOcaObjectDef_ChStatus_Ovl", "structNanoOcp1_1_1AmpDxDy_1_1dbOcaObjectDef__ChStatus__Ovl.html", "structNanoOcp1_1_1AmpDxDy_1_1dbOcaObjectDef__ChStatus__Ovl" ],
        [ "dbOcaObjectDef_Settings_PwrOn", "structNanoOcp1_1_1AmpDxDy_1_1dbOcaObjectDef__Settings__PwrOn.html", "structNanoOcp1_1_1AmpDxDy_1_1dbOcaObjectDef__Settings__PwrOn" ]
      ] ],
      [ "AmpDy", "namespaceNanoOcp1_1_1AmpDy.html", [
        [ "dbOcaObjectDef_ChStatus_GrHead", "structNanoOcp1_1_1AmpDy_1_1dbOcaObjectDef__ChStatus__GrHead.html", "structNanoOcp1_1_1AmpDy_1_1dbOcaObjectDef__ChStatus__GrHead" ]
      ] ],
      [ "AmpGeneric", "namespaceNanoOcp1_1_1AmpGeneric.html", [
        [ "dbOcaObjectDef_Config_Mute", "structNanoOcp1_1_1AmpGeneric_1_1dbOcaObjectDef__Config__Mute.html", "structNanoOcp1_1_1AmpGeneric_1_1dbOcaObjectDef__Config__Mute" ],
        [ "dbOcaObjectDef_Config_PotiLevel", "structNanoOcp1_1_1AmpGeneric_1_1dbOcaObjectDef__Config__PotiLevel.html", "structNanoOcp1_1_1AmpGeneric_1_1dbOcaObjectDef__Config__PotiLevel" ]
      ] ],
      [ "DS100", "namespaceNanoOcp1_1_1DS100.html", [
        [ "dbOcaObjDef_MatrixSettings_ReverbRoomIdEnableds", "structNanoOcp1_1_1DS100_1_1dbOcaObjDef__MatrixSettings__ReverbRoomIdEnableds.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjDef__MatrixSettings__ReverbRoomIdEnableds" ],
        [ "dbOcaObjDef_MatrixSettings_ReverbRoomIdNames", "structNanoOcp1_1_1DS100_1_1dbOcaObjDef__MatrixSettings__ReverbRoomIdNames.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjDef__MatrixSettings__ReverbRoomIdNames" ],
        [ "dbOcaObjectDef_CoordinateMapping_Source_Position", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__CoordinateMapping__Source__Position.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__CoordinateMapping__Source__Position" ],
        [ "dbOcaObjectDef_CoordinateMappingSettings_Flip", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__CoordinateMappingSettings__Flip.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__CoordinateMappingSettings__Flip" ],
        [ "dbOcaObjectDef_CoordinateMappingSettings_Name", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__CoordinateMappingSettings__Name.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__CoordinateMappingSettings__Name" ],
        [ "dbOcaObjectDef_CoordinateMappingSettings_P1_real", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__CoordinateMappingSettings__P1__real.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__CoordinateMappingSettings__P1__real" ],
        [ "dbOcaObjectDef_CoordinateMappingSettings_P1_virtual", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__CoordinateMappingSettings__P1__virtual.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__CoordinateMappingSettings__P1__virtual" ],
        [ "dbOcaObjectDef_CoordinateMappingSettings_P2_real", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__CoordinateMappingSettings__P2__real.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__CoordinateMappingSettings__P2__real" ],
        [ "dbOcaObjectDef_CoordinateMappingSettings_P3_real", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__CoordinateMappingSettings__P3__real.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__CoordinateMappingSettings__P3__real" ],
        [ "dbOcaObjectDef_CoordinateMappingSettings_P3_virtual", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__CoordinateMappingSettings__P3__virtual.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__CoordinateMappingSettings__P3__virtual" ],
        [ "dbOcaObjectDef_CoordinateMappingSettings_P4_real", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__CoordinateMappingSettings__P4__real.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__CoordinateMappingSettings__P4__real" ],
        [ "dbOcaObjectDef_CoordinateMappingSettings_Type", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__CoordinateMappingSettings__Type.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__CoordinateMappingSettings__Type" ],
        [ "dbOcaObjectDef_Error_ErrorText", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__Error__ErrorText.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__Error__ErrorText" ],
        [ "dbOcaObjectDef_Error_GnrlErr", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__Error__GnrlErr.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__Error__GnrlErr" ],
        [ "dbOcaObjectDef_Fixed_GUID", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__Fixed__GUID.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__Fixed__GUID" ],
        [ "dbOcaObjectDef_Fixed_HardwareVariant", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__Fixed__HardwareVariant.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__Fixed__HardwareVariant" ],
        [ "dbOcaObjectDef_Fixed_SerNr", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__Fixed__SerNr.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__Fixed__SerNr" ],
        [ "dbOcaObjectDef_FunctionGroup_Delay", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__FunctionGroup__Delay.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__FunctionGroup__Delay" ],
        [ "dbOcaObjectDef_FunctionGroup_Mode", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__FunctionGroup__Mode.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__FunctionGroup__Mode" ],
        [ "dbOcaObjectDef_FunctionGroup_Name", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__FunctionGroup__Name.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__FunctionGroup__Name" ],
        [ "dbOcaObjectDef_FunctionGroup_SpreadFactor", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__FunctionGroup__SpreadFactor.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__FunctionGroup__SpreadFactor" ],
        [ "dbOcaObjectDef_MatrixInput_ChannelName", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixInput__ChannelName.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixInput__ChannelName" ],
        [ "dbOcaObjectDef_MatrixInput_Delay", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixInput__Delay.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixInput__Delay" ],
        [ "dbOcaObjectDef_MatrixInput_DelayEnable", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixInput__DelayEnable.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixInput__DelayEnable" ],
        [ "dbOcaObjectDef_MatrixInput_EqEnable", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixInput__EqEnable.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixInput__EqEnable" ],
        [ "dbOcaObjectDef_MatrixInput_Gain", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixInput__Gain.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixInput__Gain" ],
        [ "dbOcaObjectDef_MatrixInput_ISP", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixInput__ISP.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixInput__ISP" ],
        [ "dbOcaObjectDef_MatrixInput_LevelMeterIn", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixInput__LevelMeterIn.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixInput__LevelMeterIn" ],
        [ "dbOcaObjectDef_MatrixInput_LevelMeterPostMute", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixInput__LevelMeterPostMute.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixInput__LevelMeterPostMute" ],
        [ "dbOcaObjectDef_MatrixInput_LevelMeterPreMute", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixInput__LevelMeterPreMute.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixInput__LevelMeterPreMute" ],
        [ "dbOcaObjectDef_MatrixInput_Mute", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixInput__Mute.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixInput__Mute" ],
        [ "dbOcaObjectDef_MatrixInput_Polarity", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixInput__Polarity.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixInput__Polarity" ],
        [ "dbOcaObjectDef_MatrixInput_ReverbSendGain", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixInput__ReverbSendGain.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixInput__ReverbSendGain" ],
        [ "dbOcaObjectDef_MatrixNode_Delay", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixNode__Delay.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixNode__Delay" ],
        [ "dbOcaObjectDef_MatrixNode_DelayEnable", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixNode__DelayEnable.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixNode__DelayEnable" ],
        [ "dbOcaObjectDef_MatrixNode_Enable", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixNode__Enable.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixNode__Enable" ],
        [ "dbOcaObjectDef_MatrixNode_Gain", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixNode__Gain.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixNode__Gain" ],
        [ "dbOcaObjectDef_MatrixOutput_ChannelName", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixOutput__ChannelName.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixOutput__ChannelName" ],
        [ "dbOcaObjectDef_MatrixOutput_Delay", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixOutput__Delay.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixOutput__Delay" ],
        [ "dbOcaObjectDef_MatrixOutput_DelayEnable", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixOutput__DelayEnable.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixOutput__DelayEnable" ],
        [ "dbOcaObjectDef_MatrixOutput_EqEnable", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixOutput__EqEnable.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixOutput__EqEnable" ],
        [ "dbOcaObjectDef_MatrixOutput_Gain", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixOutput__Gain.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixOutput__Gain" ],
        [ "dbOcaObjectDef_MatrixOutput_LevelMeterIn", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixOutput__LevelMeterIn.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixOutput__LevelMeterIn" ],
        [ "dbOcaObjectDef_MatrixOutput_LevelMeterPostMute", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixOutput__LevelMeterPostMute.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixOutput__LevelMeterPostMute" ],
        [ "dbOcaObjectDef_MatrixOutput_LevelMeterPreMute", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixOutput__LevelMeterPreMute.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixOutput__LevelMeterPreMute" ],
        [ "dbOcaObjectDef_MatrixOutput_Mute", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixOutput__Mute.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixOutput__Mute" ],
        [ "dbOcaObjectDef_MatrixOutput_OSP", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixOutput__OSP.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixOutput__OSP" ],
        [ "dbOcaObjectDef_MatrixOutput_Polarity", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixOutput__Polarity.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixOutput__Polarity" ],
        [ "dbOcaObjectDef_MatrixSettings_PositioningEnable", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixSettings__PositioningEnable.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixSettings__PositioningEnable" ],
        [ "dbOcaObjectDef_MatrixSettings_ReverbEnable", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixSettings__ReverbEnable.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixSettings__ReverbEnable" ],
        [ "dbOcaObjectDef_MatrixSettings_ReverbPredelayFactor", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixSettings__ReverbPredelayFactor.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixSettings__ReverbPredelayFactor" ],
        [ "dbOcaObjectDef_MatrixSettings_ReverbRearLevel", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixSettings__ReverbRearLevel.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixSettings__ReverbRearLevel" ],
        [ "dbOcaObjectDef_MatrixSettings_ReverbRoomId", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixSettings__ReverbRoomId.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixSettings__ReverbRoomId" ],
        [ "dbOcaObjectDef_Positioning_Source_DelayMode", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__Positioning__Source__DelayMode.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__Positioning__Source__DelayMode" ],
        [ "dbOcaObjectDef_Positioning_Source_Enable", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__Positioning__Source__Enable.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__Positioning__Source__Enable" ],
        [ "dbOcaObjectDef_Positioning_Source_Position", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__Positioning__Source__Position.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__Positioning__Source__Position" ],
        [ "dbOcaObjectDef_Positioning_Source_Speaker_Group", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__Positioning__Source__Speaker__Group.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__Positioning__Source__Speaker__Group" ],
        [ "dbOcaObjectDef_Positioning_Source_Speaker_Position", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__Positioning__Source__Speaker__Position.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__Positioning__Source__Speaker__Position" ],
        [ "dbOcaObjectDef_Positioning_Source_Spread", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__Positioning__Source__Spread.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__Positioning__Source__Spread" ],
        [ "dbOcaObjectDef_Positioning_Speaker_Group", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__Positioning__Speaker__Group.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__Positioning__Speaker__Group" ],
        [ "dbOcaObjectDef_Positioning_Speaker_Position", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__Positioning__Speaker__Position.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__Positioning__Speaker__Position" ],
        [ "dbOcaObjectDef_ReverbInput_Gain", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__ReverbInput__Gain.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__ReverbInput__Gain" ],
        [ "dbOcaObjectDef_ReverbInputProcessing_EqEnable", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__ReverbInputProcessing__EqEnable.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__ReverbInputProcessing__EqEnable" ],
        [ "dbOcaObjectDef_ReverbInputProcessing_Gain", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__ReverbInputProcessing__Gain.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__ReverbInputProcessing__Gain" ],
        [ "dbOcaObjectDef_ReverbInputProcessing_LevelMeter", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__ReverbInputProcessing__LevelMeter.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__ReverbInputProcessing__LevelMeter" ],
        [ "dbOcaObjectDef_ReverbInputProcessing_Mute", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__ReverbInputProcessing__Mute.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__ReverbInputProcessing__Mute" ],
        [ "dbOcaObjectDef_Scene_SceneComment", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__Scene__SceneComment.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__Scene__SceneComment" ],
        [ "dbOcaObjectDef_Scene_SceneIndex", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__Scene__SceneIndex.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__Scene__SceneIndex" ],
        [ "dbOcaObjectDef_Scene_SceneName", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__Scene__SceneName.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__Scene__SceneName" ],
        [ "dbOcaObjectDef_SceneAgent", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__SceneAgent.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__SceneAgent" ],
        [ "dbOcaObjectDef_Settings_DeviceName", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__Settings__DeviceName.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__Settings__DeviceName" ],
        [ "dbOcaObjectDef_SoundObjectRouting_Gain", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__SoundObjectRouting__Gain.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__SoundObjectRouting__Gain" ],
        [ "dbOcaObjectDef_SoundObjectRouting_Mute", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__SoundObjectRouting__Mute.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__SoundObjectRouting__Mute" ],
        [ "dbOcaObjectDef_Status_AudioNetworkSampleStatus", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__Status__AudioNetworkSampleStatus.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__Status__AudioNetworkSampleStatus" ],
        [ "dbOcaObjectDef_Status_StatusText", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__Status__StatusText.html", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__Status__StatusText" ]
      ] ],
      [ "AmpController", "classNanoOcp1_1_1AmpController.html", "classNanoOcp1_1_1AmpController" ],
      [ "NanoAsyncDispatcher", "classNanoOcp1_1_1NanoAsyncDispatcher.html", "classNanoOcp1_1_1NanoAsyncDispatcher" ],
      [ "NanoOcp1Base", "classNanoOcp1_1_1NanoOcp1Base.html", "classNanoOcp1_1_1NanoOcp1Base" ],
      [ "NanoOcp1Client", "classNanoOcp1_1_1NanoOcp1Client.html", "classNanoOcp1_1_1NanoOcp1Client" ],
      [ "NanoOcp1Server", "classNanoOcp1_1_1NanoOcp1Server.html", "classNanoOcp1_1_1NanoOcp1Server" ],
      [ "NanoSocket", "classNanoOcp1_1_1NanoSocket.html", "classNanoOcp1_1_1NanoSocket" ],
      [ "NanoThread", "classNanoOcp1_1_1NanoThread.html", "classNanoOcp1_1_1NanoThread" ],
      [ "NanoTimer", "classNanoOcp1_1_1NanoTimer.html", "classNanoOcp1_1_1NanoTimer" ],
      [ "Ocp1CommandDefinition", "structNanoOcp1_1_1Ocp1CommandDefinition.html", "structNanoOcp1_1_1Ocp1CommandDefinition" ],
      [ "Ocp1CommandResponseRequired", "classNanoOcp1_1_1Ocp1CommandResponseRequired.html", "classNanoOcp1_1_1Ocp1CommandResponseRequired" ],
      [ "Ocp1Connection", "classNanoOcp1_1_1Ocp1Connection.html", "classNanoOcp1_1_1Ocp1Connection" ],
      [ "Ocp1ConnectionServer", "classNanoOcp1_1_1Ocp1ConnectionServer.html", "classNanoOcp1_1_1Ocp1ConnectionServer" ],
      [ "Ocp1Controller", "classNanoOcp1_1_1Ocp1Controller.html", "classNanoOcp1_1_1Ocp1Controller" ],
      [ "Ocp1Header", "classNanoOcp1_1_1Ocp1Header.html", "classNanoOcp1_1_1Ocp1Header" ],
      [ "Ocp1KeepAlive", "classNanoOcp1_1_1Ocp1KeepAlive.html", "classNanoOcp1_1_1Ocp1KeepAlive" ],
      [ "Ocp1Message", "classNanoOcp1_1_1Ocp1Message.html", "classNanoOcp1_1_1Ocp1Message" ],
      [ "Ocp1Notification", "classNanoOcp1_1_1Ocp1Notification.html", "classNanoOcp1_1_1Ocp1Notification" ],
      [ "Ocp1Response", "classNanoOcp1_1_1Ocp1Response.html", "classNanoOcp1_1_1Ocp1Response" ],
      [ "SafeActionImpl", "classNanoOcp1_1_1SafeActionImpl.html", "classNanoOcp1_1_1SafeActionImpl" ],
      [ "SoundscapeController", "classNanoOcp1_1_1SoundscapeController.html", "classNanoOcp1_1_1SoundscapeController" ],
      [ "Variant", "classNanoOcp1_1_1Variant.html", "classNanoOcp1_1_1Variant" ]
    ] ],
    [ "AppState", "structAppState.html", "structAppState" ],
    [ "ChState", "structChState.html", "structChState" ],
    [ "Demo", "classDemo.html", "classDemo" ],
    [ "FocusParamEntry", "structFocusParamEntry.html", "structFocusParamEntry" ]
];