var hierarchy =
[
    [ "AppState::AmpState", "structAppState_1_1AmpState.html", null ],
    [ "AppState", "structAppState.html", null ],
    [ "ChState", "structChState.html", null ],
    [ "Demo::Config", "structDemo_1_1Config.html", null ],
    [ "Demo", "classDemo.html", null ],
    [ "FocusParamEntry", "structFocusParamEntry.html", null ],
    [ "AppState::FocusState", "structAppState_1_1FocusState.html", null ],
    [ "NanoOcp1::NanoAsyncDispatcher", "classNanoOcp1_1_1NanoAsyncDispatcher.html", null ],
    [ "NanoOcp1::NanoOcp1Base", "classNanoOcp1_1_1NanoOcp1Base.html", [
      [ "NanoOcp1::NanoOcp1Client", "classNanoOcp1_1_1NanoOcp1Client.html", null ],
      [ "NanoOcp1::NanoOcp1Server", "classNanoOcp1_1_1NanoOcp1Server.html", null ]
    ] ],
    [ "NanoOcp1::NanoSocket", "classNanoOcp1_1_1NanoSocket.html", null ],
    [ "NanoOcp1::NanoThread", "classNanoOcp1_1_1NanoThread.html", [
      [ "NanoOcp1::Ocp1Connection::ConnectionThread", "structNanoOcp1_1_1Ocp1Connection_1_1ConnectionThread.html", null ],
      [ "NanoOcp1::Ocp1ConnectionServer", "classNanoOcp1_1_1Ocp1ConnectionServer.html", [
        [ "NanoOcp1::NanoOcp1Server", "classNanoOcp1_1_1NanoOcp1Server.html", null ]
      ] ]
    ] ],
    [ "NanoOcp1::NanoTimer", "classNanoOcp1_1_1NanoTimer.html", [
      [ "NanoOcp1::NanoOcp1Client", "classNanoOcp1_1_1NanoOcp1Client.html", null ],
      [ "NanoOcp1::Ocp1Controller", "classNanoOcp1_1_1Ocp1Controller.html", [
        [ "NanoOcp1::AmpController", "classNanoOcp1_1_1AmpController.html", null ],
        [ "NanoOcp1::SoundscapeController", "classNanoOcp1_1_1SoundscapeController.html", null ]
      ] ]
    ] ],
    [ "NanoOcp1::Ocp1CommandDefinition", "structNanoOcp1_1_1Ocp1CommandDefinition.html", [
      [ "NanoOcp1::Amp5D::dbOcaObjectDef_ChStatus_Gr", "structNanoOcp1_1_1Amp5D_1_1dbOcaObjectDef__ChStatus__Gr.html", null ],
      [ "NanoOcp1::Amp5D::dbOcaObjectDef_ChStatus_GrHead", "structNanoOcp1_1_1Amp5D_1_1dbOcaObjectDef__ChStatus__GrHead.html", null ],
      [ "NanoOcp1::Amp5D::dbOcaObjectDef_ChStatus_Isp", "structNanoOcp1_1_1Amp5D_1_1dbOcaObjectDef__ChStatus__Isp.html", null ],
      [ "NanoOcp1::Amp5D::dbOcaObjectDef_ChStatus_Ovl", "structNanoOcp1_1_1Amp5D_1_1dbOcaObjectDef__ChStatus__Ovl.html", null ],
      [ "NanoOcp1::Amp5D::dbOcaObjectDef_Settings_PwrOn", "structNanoOcp1_1_1Amp5D_1_1dbOcaObjectDef__Settings__PwrOn.html", null ],
      [ "NanoOcp1::AmpDx::dbOcaObjectDef_ChStatus_GrHead", "structNanoOcp1_1_1AmpDx_1_1dbOcaObjectDef__ChStatus__GrHead.html", null ],
      [ "NanoOcp1::AmpDxDy::dbOcaObjectDef_ChStatus_Gr", "structNanoOcp1_1_1AmpDxDy_1_1dbOcaObjectDef__ChStatus__Gr.html", null ],
      [ "NanoOcp1::AmpDxDy::dbOcaObjectDef_ChStatus_Isp", "structNanoOcp1_1_1AmpDxDy_1_1dbOcaObjectDef__ChStatus__Isp.html", null ],
      [ "NanoOcp1::AmpDxDy::dbOcaObjectDef_ChStatus_Ovl", "structNanoOcp1_1_1AmpDxDy_1_1dbOcaObjectDef__ChStatus__Ovl.html", null ],
      [ "NanoOcp1::AmpDxDy::dbOcaObjectDef_Settings_PwrOn", "structNanoOcp1_1_1AmpDxDy_1_1dbOcaObjectDef__Settings__PwrOn.html", null ],
      [ "NanoOcp1::AmpDy::dbOcaObjectDef_ChStatus_GrHead", "structNanoOcp1_1_1AmpDy_1_1dbOcaObjectDef__ChStatus__GrHead.html", null ],
      [ "NanoOcp1::AmpGeneric::dbOcaObjectDef_Config_Mute", "structNanoOcp1_1_1AmpGeneric_1_1dbOcaObjectDef__Config__Mute.html", null ],
      [ "NanoOcp1::AmpGeneric::dbOcaObjectDef_Config_PotiLevel", "structNanoOcp1_1_1AmpGeneric_1_1dbOcaObjectDef__Config__PotiLevel.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjDef_MatrixSettings_ReverbRoomIdEnableds", "structNanoOcp1_1_1DS100_1_1dbOcaObjDef__MatrixSettings__ReverbRoomIdEnableds.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjDef_MatrixSettings_ReverbRoomIdNames", "structNanoOcp1_1_1DS100_1_1dbOcaObjDef__MatrixSettings__ReverbRoomIdNames.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_CoordinateMappingSettings_Flip", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__CoordinateMappingSettings__Flip.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_CoordinateMappingSettings_Name", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__CoordinateMappingSettings__Name.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_CoordinateMappingSettings_P1_real", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__CoordinateMappingSettings__P1__real.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_CoordinateMappingSettings_P1_virtual", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__CoordinateMappingSettings__P1__virtual.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_CoordinateMappingSettings_P2_real", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__CoordinateMappingSettings__P2__real.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_CoordinateMappingSettings_P3_real", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__CoordinateMappingSettings__P3__real.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_CoordinateMappingSettings_P3_virtual", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__CoordinateMappingSettings__P3__virtual.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_CoordinateMappingSettings_P4_real", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__CoordinateMappingSettings__P4__real.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_CoordinateMappingSettings_Type", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__CoordinateMappingSettings__Type.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_CoordinateMapping_Source_Position", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__CoordinateMapping__Source__Position.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_Error_ErrorText", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__Error__ErrorText.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_Error_GnrlErr", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__Error__GnrlErr.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_Fixed_GUID", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__Fixed__GUID.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_Fixed_HardwareVariant", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__Fixed__HardwareVariant.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_Fixed_SerNr", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__Fixed__SerNr.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_FunctionGroup_Delay", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__FunctionGroup__Delay.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_FunctionGroup_Mode", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__FunctionGroup__Mode.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_FunctionGroup_Name", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__FunctionGroup__Name.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_FunctionGroup_SpreadFactor", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__FunctionGroup__SpreadFactor.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_MatrixInput_ChannelName", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixInput__ChannelName.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_MatrixInput_Delay", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixInput__Delay.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_MatrixInput_DelayEnable", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixInput__DelayEnable.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_MatrixInput_EqEnable", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixInput__EqEnable.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_MatrixInput_Gain", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixInput__Gain.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_MatrixInput_ISP", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixInput__ISP.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_MatrixInput_LevelMeterIn", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixInput__LevelMeterIn.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_MatrixInput_LevelMeterPostMute", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixInput__LevelMeterPostMute.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_MatrixInput_LevelMeterPreMute", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixInput__LevelMeterPreMute.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_MatrixInput_Mute", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixInput__Mute.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_MatrixInput_Polarity", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixInput__Polarity.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_MatrixInput_ReverbSendGain", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixInput__ReverbSendGain.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_MatrixNode_Delay", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixNode__Delay.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_MatrixNode_DelayEnable", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixNode__DelayEnable.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_MatrixNode_Enable", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixNode__Enable.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_MatrixNode_Gain", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixNode__Gain.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_MatrixOutput_ChannelName", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixOutput__ChannelName.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_MatrixOutput_Delay", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixOutput__Delay.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_MatrixOutput_DelayEnable", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixOutput__DelayEnable.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_MatrixOutput_EqEnable", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixOutput__EqEnable.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_MatrixOutput_Gain", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixOutput__Gain.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_MatrixOutput_LevelMeterIn", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixOutput__LevelMeterIn.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_MatrixOutput_LevelMeterPostMute", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixOutput__LevelMeterPostMute.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_MatrixOutput_LevelMeterPreMute", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixOutput__LevelMeterPreMute.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_MatrixOutput_Mute", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixOutput__Mute.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_MatrixOutput_OSP", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixOutput__OSP.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_MatrixOutput_Polarity", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixOutput__Polarity.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_MatrixSettings_PositioningEnable", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixSettings__PositioningEnable.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_MatrixSettings_ReverbEnable", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixSettings__ReverbEnable.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_MatrixSettings_ReverbPredelayFactor", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixSettings__ReverbPredelayFactor.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_MatrixSettings_ReverbRearLevel", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixSettings__ReverbRearLevel.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_MatrixSettings_ReverbRoomId", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__MatrixSettings__ReverbRoomId.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_Positioning_Source_DelayMode", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__Positioning__Source__DelayMode.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_Positioning_Source_Enable", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__Positioning__Source__Enable.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_Positioning_Source_Position", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__Positioning__Source__Position.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_Positioning_Source_Speaker_Group", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__Positioning__Source__Speaker__Group.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_Positioning_Source_Speaker_Position", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__Positioning__Source__Speaker__Position.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_Positioning_Source_Spread", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__Positioning__Source__Spread.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_Positioning_Speaker_Group", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__Positioning__Speaker__Group.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_Positioning_Speaker_Position", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__Positioning__Speaker__Position.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_ReverbInputProcessing_EqEnable", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__ReverbInputProcessing__EqEnable.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_ReverbInputProcessing_Gain", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__ReverbInputProcessing__Gain.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_ReverbInputProcessing_LevelMeter", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__ReverbInputProcessing__LevelMeter.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_ReverbInputProcessing_Mute", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__ReverbInputProcessing__Mute.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_ReverbInput_Gain", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__ReverbInput__Gain.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_SceneAgent", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__SceneAgent.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_Scene_SceneComment", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__Scene__SceneComment.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_Scene_SceneIndex", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__Scene__SceneIndex.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_Scene_SceneName", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__Scene__SceneName.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_Settings_DeviceName", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__Settings__DeviceName.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_SoundObjectRouting_Gain", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__SoundObjectRouting__Gain.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_SoundObjectRouting_Mute", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__SoundObjectRouting__Mute.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_Status_AudioNetworkSampleStatus", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__Status__AudioNetworkSampleStatus.html", null ],
      [ "NanoOcp1::DS100::dbOcaObjectDef_Status_StatusText", "structNanoOcp1_1_1DS100_1_1dbOcaObjectDef__Status__StatusText.html", null ]
    ] ],
    [ "NanoOcp1::Ocp1Connection", "classNanoOcp1_1_1Ocp1Connection.html", [
      [ "NanoOcp1::NanoOcp1Client", "classNanoOcp1_1_1NanoOcp1Client.html", null ]
    ] ],
    [ "NanoOcp1::Ocp1Header", "classNanoOcp1_1_1Ocp1Header.html", null ],
    [ "NanoOcp1::Ocp1Message", "classNanoOcp1_1_1Ocp1Message.html", [
      [ "NanoOcp1::Ocp1CommandResponseRequired", "classNanoOcp1_1_1Ocp1CommandResponseRequired.html", null ],
      [ "NanoOcp1::Ocp1KeepAlive", "classNanoOcp1_1_1Ocp1KeepAlive.html", null ],
      [ "NanoOcp1::Ocp1Notification", "classNanoOcp1_1_1Ocp1Notification.html", null ],
      [ "NanoOcp1::Ocp1Response", "classNanoOcp1_1_1Ocp1Response.html", null ]
    ] ],
    [ "NanoOcp1::SoundscapeController::RemObjAddr", "structNanoOcp1_1_1SoundscapeController_1_1RemObjAddr.html", null ],
    [ "NanoOcp1::SoundscapeController::RemoteObject", "structNanoOcp1_1_1SoundscapeController_1_1RemoteObject.html", null ],
    [ "NanoOcp1::SafeActionImpl", "classNanoOcp1_1_1SafeActionImpl.html", [
      [ "NanoOcp1::Ocp1Connection::SafeAction", "classNanoOcp1_1_1Ocp1Connection_1_1SafeAction.html", null ]
    ] ],
    [ "AppState::SoState", "structAppState_1_1SoState.html", null ],
    [ "NanoOcp1::Variant", "classNanoOcp1_1_1Variant.html", null ]
];