name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            name: macOS
          - os: ubuntu-latest
            name: Linux
          - os: windows-latest
            name: Windows

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure
        run: >
          cmake -B build -S .
          -DNANOOCP1_BUILD_DEMO=ON
          -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release
